language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - cd  ./tests && nosetests
branches:
  only: develop
after_success:
  - coveralls
