language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
env:
  - DB=postgres

before_script:
  - psql -c 'CREATE ROLE test_user WITH LOGIN PASSWORD 'default' NOSUPERUSER INHERIT CREATEDB;' -U postgres
  - psql -c 'create database test_db;' -U postgres
script:
  - cd  ./tests && nosetests
branches:
  only: develop
after_success:
  - coveralls
