language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
env:
  - DB=postgres

before_script:
  - psql -c "CREATE ROLE test_user WITH LOGIN PASSWORD 'default' NOSUPERUSER INHERIT CREATEDB;" -U postgres
  - psql -c 'create database test_db;' -U postgres
script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app
  - coveralls
  - codecov
branches:
  only: develop
after_success:
  - "coveralls"
