"""empty message

Revision ID: 147bb8bfc55d
Revises: 638c457565f2
Create Date: 2018-03-28 16:34:38.999180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147bb8bfc55d'
down_revision = '638c457565f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('pwd_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('business',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('reviews',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('review_for', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_for'], ['business.bid'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('business')
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
